baseURL = 'https://skytomo221.github.io'
defaultContentLanguage = "ja"
hasCJKLanguage = true
languageCode = 'ja-jp'
title = 'skytomo'

[markup.goldmark.renderer]
hardWraps = true
[markup.highlight]
lineNos = true
